const Catalogo = [
    {
        id: "origins_of_men",
        texto: {
            titulo: "Origins of men, the actual knowldge. Fundamental mistake.",
            material: "Mixta de acuarela y collage sobre papel de algodón.",
            anyo: "2023",
            autor: "Mena Sáenz",
            acerca_obra: "Uno de los errores más comentados por las epistemologías del sur y el feminismo latinoamericano es el de centrar al hombre representante de la cultura greco-romana como la máxima de la civilización y la creación. Se discute la hegemonía cultural producto de las colonizaciones y las guerras de los hombres. La institución del patriarcado como sistema en que la  colonialidad es destino y origen de las lógicas masculinas a través de preguntarnos por el portal entre la nada y la vida, la capacidad de encarnar en el mundo en medio de las piernas de hasta las más simples y humildes mujeres. Capacidad creativa divina y desafiante que es exclusiva de la hembra humana. ¿De dónde vienen todos esos hombres engrandecidos? ¿Por qué las mujeres han pagado históricamente como botín de sus errores?",
        },
        img: "img/galeria/origins_men_art.JPG",
    },
    {
        id: "cuadernos_amor_1",
        texto: {
            titulo: "arte de las series \"Los Cuadernos del Amor\"",
            material: "Ilustración",
            anyo: "2011",
            autor: "Erick Nungaray",
            acerca_obra: "Los Cuadernos del Amor fue una serie de dibujos realizada entre el 2010 y 2014 que ilustra irónicamente el amor y el  fracaso.",
        },
        img: "img/galeria/cuadernos_amor_1.jpg",
    },
    {
        id: "cuadernos_amor_2",
        texto: {
            titulo: "arte de las series \"Los Cuadernos del Amor\"",
            material: "Ilustración",
            anyo: "2011",
            autor: "Erick Nungaray",
            acerca_obra: "Los Cuadernos del Amor fue una serie de dibujos realizada entre el 2010 y 2014 que ilustra irónicamente el amor y el  fracaso.",
        },
        img: "img/galeria/cuadernos_amor_2.jpg",
    },
    {
        id: "opuntita",
        texto: {
            titulo: "Opuntia engelmannii var. aciculata",
            tecnica: "Mixta; acuarela en pasta con lápices suaves",
            material: "Papel Canson Mix media 300g-  22.9 cm x 30.5 cm",
            anyo: "2020",
            autor: "Eugenia Alaniz Fierro",
            acerca_obra: " Esta obra inicialmente fue pensada para la identificación de un ejemplar de O. engelmannii, sin embargo, durante su observación. Se determino que por aspectos morfológicos no era la especie con la que se trabajaba, si no una variedad de la misma especie, el detalle de las espinas fue un elemento crucial para su identificación, siendo las técnicas empleadas en la ilustración lo que permitió darle un toque especial a la ilustración como su apreciación. Esto dio pie a volverse una obra más de una serie de ilustraciones científicas sobre cactaceas.",
        },
        img: "img/galeria/opuntita.jpeg",
    },
    {
        id: "lado_b",
        texto: {
            titulo: "Lado B del Lado B",
            tecnica: "Videoarte",
            anyo: "2021",
            autor: "Pablo Aguirre",
            acerca_obra: "La naturaleza efímera y anónima de las comunicaciones en línea promueve una apariencia de libertad similar a las conversaciones privadas. Sin embargo, esta libertad también propicia la propagación del error y la desinformación. A través de rumores, teorías conspirativas y emociones desbordadas expresadas sin filtro ni verificación, el error y la información falsa se cuelan y consolidan momentáneamente en el espacio público virtual. Este trabajo analiza conversaciones de WhatsApp durante la pandemia para desentrañar las estructuras conceptuales inconsistentes y llenas de contradicciones que subyacen a las fracturas sociopolíticas, y la materialidad fértil pero también problemática que encierran los impulsos irracionales expresados en una época de incertidumbre. Todo ello a través de un \"hackeo estadístico\" que problematiza la inestable pero reveladora arquitectura del error y el sinsentido en las comunicaciones digitales. \n\n\n\nPresentado en el Centro Cultural de España en La Paz-Bolivia. Dentro de la exposición colectiva \"Mutaciones y afecciones #cuerpospandemicos\". ",
        },
        video: "img/galeria/lado_b_2_3.mp4",
    },
    {
        id: "triptico_baja_res",
        texto: {
            titulo: "Triptico a Baja Resolución Pt2",
            material: "",
            tecnica: "Óleo sobre mdf",
            anyo: "2023",
            autor: "Misael Osorio (misa.09)",
            acerca_obra: "Esta es una obra que nace de la inquietud de llevar una imagen de índole digital a un contexto análogo, el jugar con la forma en que ha sido creada genera de cerca la impresión de algo abstracto y aleatorio, sin embargo al tomar distancia con al obra se logra apreciar la imagen, esta pertenece a una serie de 3 obras llevadas a cabo bajo la misma perspectiva, y representan de manera muy personal una manera de afrontar los miedos, la muerte, el cansancio.",
        },
        img: "img/galeria/triptico_baja_res.jpg",
    },

    {
        id: "literatura_glitch",
        texto: {
            titulo: "Ninety-nine tweets about #LiteracyOfTheGlitch: a #LessonPlan on the potentials of failure, the unforeseen & the errant.",
            material: "",
            tecnica: "",
            anyo: "2012",
            autor: "León de la Rosa",
            acerca_obra: "Artista, activista por el Valle de Juárez ( Artivista ) y poeta desde el border León de la Rosa se dedica al remix de situaciones y palabras. Reorganiza y desorganiza la realidad a través de sus repeticiones que luego se convierten en retruécanos, en monólogos, en diálogos o cualquier cosa que sea la comunicación después de criticar al sistema en que somos y nos comunicamos en este glitch que llamamos sociedad.",
            visitar_sitio: "https://literacyoftheglitch.org/",
        },
        img: "img/galeria/literatura_glitch.gif",
    },
    {
        id: "nada_ojala",
        texto: {
            titulo: "Post/Nada_[as in Reporte Ojalá]",
            material: "",
            tecnica: "",
            anyo: "2013-2014",
            autor: "León de la Rosa",
            acerca_obra: "Artista, activista por el Valle de Juárez ( Artivista ) y poeta desde el border León de la Rosa se dedica al remix de situaciones y palabras. Reorganiza y desorganiza la realidad a través de sus repeticiones que luego se convierten en retruécanos, en monólogos, en diálogos o cualquier cosa que sea la comunicación después de criticar al sistema en que somos y nos comunicamos en este glitch que llamamos sociedad.",
            visitar_sitio: "https://nadawholeojala.wordpress.com/",
        },
        img: "img/galeria/nada_ojala.gif",
    },
    {
        id: "arboles_windsong",
        texto: {
            titulo: "Arboles-WindSongs",
            material: "",
            tecnica: "",
            anyo: "2017-2021",
            autor: "León de la Rosa",
            acerca_obra: "Artista, activista por el Valle de Juárez ( Artivista ) y poeta desde el border León de la Rosa se dedica al remix de situaciones y palabras. Reorganiza y desorganiza la realidad a través de sus repeticiones que luego se convierten en retruécanos, en monólogos, en diálogos o cualquier cosa que sea la comunicación después de criticar al sistema en que somos y nos comunicamos en este glitch que llamamos sociedad.",
            visitar_sitio: "https://sinlinea.net/Arboles-WindSongs/index.html",
        },
        img: "img/galeria/arboles_windsong.png",
    },
    {
        id: "obra_eugenia_1",
        texto: {
            titulo: "anti taxonomía o como me salí de control",
            material: "",
            tecnica: "fotografía digital",
            anyo: "2019",
            autor: "Ma. Eugenia Hernandez Sánchez",
            acerca_obra: "Ma. Eugenia Hernandez Sánchez es investigadora, docente, artista y activista especialista en migración, infancias y teoría de género en la frontera Norte de México. ",
            visitar_sitio: "",
        },
        img: "img/galeria/obra_eugenia_1.jpg",
    },
    {
        id: "obra_eugenia_2",
        texto: {
            titulo: "anti taxonomía o como me salí de control",
            material: "",
            tecnica: "fotografía digital",
            anyo: "2019",
            autor: "Ma. Eugenia Hernandez Sánchez",
            acerca_obra: "Ma. Eugenia Hernandez Sánchez es investigadora, docente, artista y activista especialista en migración, infancias y teoría de género en la frontera Norte de México. ",
            visitar_sitio: "",
        },
        img: "img/galeria/obra_eugenia_2.jpg",
    },
    {
        id: "obra_eugenia_3",
        texto: {
            titulo: "anti taxonomía o como me salí de control",
            material: "",
            tecnica: "fotografía digital",
            anyo: "2019",
            autor: "Ma. Eugenia Hernandez Sánchez",
            acerca_obra: "Ma. Eugenia Hernandez Sánchez es investigadora, docente, artista y activista especialista en migración, infancias y teoría de género en la frontera Norte de México. ",
            visitar_sitio: "",
        },
        img: "img/galeria/obra_eugenia_3.jpg",
    },
    {
        id: "--",
        texto: {
            titulo: "",
            material: "",
            tecnica: "",
            anyo: "",
            autor: "",
            acerca_obra: "",
            visitar_sitio: "",
        },
        img: "img/galeria/",
    },
]



